env:
  global:
    - ANDROID_API_LEVEL=27
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_ABI="default;armeabi-v7a"
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
language: android

jdk:
- oraclejdk8

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid

before_install:
# Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" >/dev/null
# Install the rest of tools (e.g., avdmanager)
- sdkmanager tools
# Install the system image
#- sdkmanager "system-images;android-$ANDROID_API_LEVEL;$ANDROID_ABI" >/dev/null
- sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI" >/dev/null
- sdkmanager --list
# Create and start emulator for the script.
- echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
- $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader &

before_script:
- android-wait-for-emulator
- adb shell input keyevent 82
- $ANDROID_HOME/emulator/emulator -list-avds
# install flutter
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
- flutter precache
- yes "y" | flutter doctor --android-licenses
- flutter doctor -v
- flutter upgrade
- flutter devices
- flutter emulators
- export device_id=`flutter devices | grep emulator | awk 'BEGIN {FS="• | •"} {print $2}'`
- echo device_id = $device_id
script:
  - ./script/runDriver.sh $device_id
#  - cd example/vanilla
#  - flutter -v drive test_driver/todo_app.dart
sudo: false

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.pub-cache
